version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Cloudlink
  - jsons
  - Longman
  - penguinmod
  - pumpkinhasapatch
  - qxsck
  - SIPC
  - Skyhigh
  - Veggiecan
ignoreWords: []
import: []
